export const BRANDS_BY_CONTEXT: Record<string, string[]> = {
  // --- Electronics ---
  smartphone: [
    "Apple",
    "Samsung",
    "Google",
    "OnePlus",
    "Xiaomi",
    "Nothing",
    "Oppo",
    "Vivo",
    "Realme",
    "Motorola",
    "iQOO",
    "Honor",
  ],

  laptop: [
    "Dell",
    "HP",
    "Lenovo",
    "Asus",
    "Acer",
    "Apple",
    "MSI",
    "Microsoft",
    "Razer",
    "Samsung",
    "LG",
  ],

  tablet: [
    "Apple",
    "Samsung",
    "Lenovo",
    "Xiaomi",
    "Microsoft",
    "Realme",
    "Honor",
  ],

  // --- Fashion: Apparel ---
  "apparel-men": [
    "Levi's",
    "Allen Solly",
    "Van Heusen",
    "Peter England",
    "Jack & Jones",
    "Louis Philippe",
    "Roadster",
    "Nike",
    "Adidas",
    "Puma",
    "H&M",
    "Zara",
    "Uniqlo",
    "Tommy Hilfiger",
    "U.S. Polo Assn.",
  ],

  "apparel-women": [
    "Zara",
    "H&M",
    "Biba",
    "W for Woman",
    "Fabindia",
    "Mango",
    "Forever 21",
    "Levi's",
    "Nike",
    "Adidas",
    "Puma",
    "ONLY",
    "Vero Moda",
    "Global Desi",
  ],

  "apparel-kids": [
    "H&M",
    "Mothercare",
    "FirstCry",
    "Gini & Jony",
    "Adidas",
    "Nike",
    "U.S. Polo Assn.",
    "Pantaloons",
    "Zara Kids",
  ],

  "apparel-unisex": [
    "Nike",
    "Adidas",
    "Puma",
    "H&M",
    "Zara",
    "Uniqlo",
    "Roadster",
  ],

  // --- Fashion: Footwear ---
  "footwear-men": [
    "Nike",
    "Adidas",
    "Puma",
    "Reebok",
    "Skechers",
    "Clarks",
    "Woodland",
    "Bata",
    "Crocs",
    "Asics",
    "Red Tape",
    "Hush Puppies",
  ],

  "footwear-women": [
    "Nike",
    "Adidas",
    "Puma",
    "Skechers",
    "Aldo",
    "Steve Madden",
    "Bata",
    "Crocs",
    "Catwalk",
    "Metro",
    "Mochi",
  ],

  "footwear-kids": [
    "Nike",
    "Adidas",
    "Puma",
    "Skechers",
    "Bata",
    "Crocs",
    "Clarks",
  ],

  "footwear-unisex": ["Nike", "Adidas", "Puma", "Skechers", "Crocs", "Asics"],

  // --- Fashion: Accessories ---
  "accessories-women": [
    "Gucci",
    "Prada",
    "Michael Kors",
    "Fossil",
    "Titan",
    "Ray-Ban",
    "Casio",
    "Lavie",
    "Caprese",
    "Baggit",
    "Accessorize",
  ],

  "accessories-men": [
    "Rolex",
    "Casio",
    "Titan",
    "Fossil",
    "Ray-Ban",
    "Tommy Hilfiger",
    "Oakley",
    "Wildhorn",
    "Fastrack",
    "Police",
  ],

  "accessories-kids": ["Fastrack", "Titan", "Casio", "Nike", "Adidas"],

  "accessories-unisex": [
    "Fastrack",
    "Casio",
    "Titan",
    "Ray-Ban",
    "Oakley",
    "Wildcraft",
  ],

  // --- Automotive ---
  automotive: [
    "Tesla",
    "BMW",
    "Mercedes-Benz",
    "Audi",
    "Toyota",
    "Honda",
    "Tata Motors",
    "Mahindra",
    "Maruti Suzuki",
    "Hyundai",
    "Kia",
  ],
};
