export const BRANDS_BY_DEPT: Record<string, string[]> = {
  electronics: [
    "Samsung",
    "Apple",
    "Sony",
    "Google",
    "OnePlus",
    "Xiaomi",
    "Nothing",
    "Dell",
    "HP",
    "Lenovo",
    "Asus",
    "Acer",
    "Microsoft",
    "LG",
    "Panasonic",
    "Realme",
    "Oppo",
    "Vivo",
    "Motorola",
    "Nokia",
    "Intel",
    "AMD",
    "Nvidia",
    "Corsair",
    "Logitech",
    "Razer",
  ],

  fashion: [
    "Zara",
    "H&M",
    "Nike",
    "Adidas",
    "Levi's",
    "Puma",
    "Roadster",
    "Uniqlo",
    "Gucci",
    "Louis Vuitton",
    "Prada",
    "Versace",
    "Burberry",
    "Tommy Hilfiger",
    "Calvin Klein",
    "Under Armour",
    "Reebok",
    "Forever 21",
    "Gap",
    "Mango",
    "Biba",
    "W for Woman",
    "Fabindia",
    "Allen Solly",
    "Van Heusen",
    "Peter England",
  ],

  automotive: [
    "Tesla",
    "BMW",
    "Mercedes-Benz",
    "Audi",
    "Toyota",
    "Honda",
    "Hyundai",
    "Kia",
    "Ford",
    "Chevrolet",
    "Volkswagen",
    "Skoda",
    "Nissan",
    "Renault",
    "Jaguar",
    "Land Rover",
    "Volvo",
    "Porsche",
    "Ferrari",
    "Lamborghini",
    "Bentley",
    "Rolls-Royce",
    "Mahindra",
    "Tata Motors",
    "Maruti Suzuki",
  ],
};
