export type GenderType = "women" | "men" | "kids" | "unisex";
export type FashionType = "apparel" | "footwear" | "accessories";

export const FASHION_CATEGORIES: Record<
  FashionType,
  Record<GenderType, string[]>
> = {
  // ================= APPAREL =================
  apparel: {
    women: [
      "Dress",
      "Kurti",
      "Saree",
      "Lehenga",
      "Top",
      "Blouse",
      "Shirt",
      "T-shirt",
      "Jeans",
      "Trousers",
      "Leggings",
      "Palazzo",
      "Skirt",
      "Jacket",
      "Shrug",
      "Sweater",
      "Sweatshirt",
      "Hoodie",
      "Suit Set",
      "Co-ord Set",
      "Ethnic Set",
      "Dupatta",
      "Jumpsuit",
      "Playsuit",
      "Nightwear",
      "Innerwear",
      "Sportswear",
      "Track Pants",
      "Joggers",
    ],

    men: [
      "Shirt",
      "T-shirt",
      "Jeans",
      "Trousers",
      "Shorts",
      "Track Pants",
      "Joggers",
      "Track Suit",
      "Kurta",
      "Ethnic Set",
      "Sherwani",
      "Suit",
      "Blazer",
      "Waistcoat",
      "Jacket",
      "Sweater",
      "Sweatshirt",
      "Hoodie",
      "Co-ord Set",
      "Innerwear",
      "Nightwear",
      "Sportswear",
    ],

    kids: [
      "Frock",
      "Dress",
      "T-shirt",
      "Shirt",
      "Top",
      "Jeans",
      "Trousers",
      "Shorts",
      "Leggings",
      "Track Pants",
      "Joggers",
      "Onesie",
      "Jacket",
      "Sweater",
      "Sweatshirt",
      "Hoodie",
      "Ethnic Set",
      "School Uniform",
      "Nightwear",
      "Innerwear",
    ],

    unisex: [
      "T-shirt",
      "Shirt",
      "Hoodie",
      "Sweatshirt",
      "Jacket",
      "Track Pants",
      "Joggers",
      "Shorts",
      "Co-ord Set",
      "Sweater",
      "Sportswear",
    ],
  },

  // ================= FOOTWEAR =================
  footwear: {
    women: [
      "Heels",
      "Heeled Sandals",
      "Flats",
      "Sandals",
      "Sneakers",
      "Boots",
      "Loafers",
      "Sports Shoes",
      "Flip Flops",
      "Sliders",
      "Ethnic Footwear",
    ],

    men: [
      "Formal Shoes",
      "Casual Shoes",
      "Sneakers",
      "Boots",
      "Sandals",
      "Loafers",
      "Sports Shoes",
      "Flip Flops",
      "Sliders",
      "Ethnic Footwear",
    ],

    kids: [
      "School Shoes",
      "Sneakers",
      "Sandals",
      "Boots",
      "Casual Shoes",
      "Flip Flops",
      "Sliders",
    ],

    unisex: ["Sneakers", "Sports Shoes", "Slippers", "Flip Flops", "Sliders"],
  },

  // ================= ACCESSORIES =================
  accessories: {
    women: [
      "Handbag",
      "Clutch",
      "Backpack",
      "Jewelry",
      "Sunglasses",
      "Watch",
      "Belts",
      "Scarf",
      "Hair Accessories",
      "Socks",
      "Stockings",
    ],

    men: [
      "Wallets",
      "Belts",
      "Watch",
      "Sunglasses",
      "Tie",
      "Caps",
      "Cufflinks",
      "Socks",
    ],

    kids: ["School Bags", "Backpacks", "Caps", "Sunglasses", "Watch", "Socks"],

    unisex: ["Backpacks", "Caps", "Sunglasses", "Watch", "Socks", "Gloves"],
  },
};
