export type GenderType = "women" | "men" | "kids" | "unisex";

export const FASHION_SUB_CATEGORIES: Record<GenderType, string[]> = {
  women: [
    "Dress",
    "Kurti",
    "Saree",
    "Lehenga",
    "Top",
    "Jeans",
    "Trousers",
    "Skirt",
    "Jacket",
    "Suit set",
    "Nightwear",
    "Sportswear",
  ],
  men: [
    "Shirt",
    "T-shirt",
    "Jeans",
    "Trousers",
    "Kurta",
    "Suit",
    "Jacket",
    "Shorts",
    "Ethnic set",
    "Innerwear",
    "Sportswear",
    "Sweatshirt",
  ],
  kids: [
    "Frock",
    "T-shirt",
    "Shorts",
    "Onesie",
    "School Uniform",
    "Ethnic Wear",
    "Nightwear",
  ],
  unisex: [
    "T-shirt",
    "Hoodie",
    "Shorts",
    "Track pants",
    "Sweatshirt",
    "Jacket",
    "Joggers",
  ],
};
