import { useReducer, useEffect } from "react";
import { getVariantConfig } from "@/common/configs/variant-mapping";
import { taxApi } from "@/lib/api/tax.api";
import type {
  InventoryProduct,
  CategoryType,
  Variant,
  SpecEntry,
} from "@/types/inventory";

type Action =
  | { type: "SET_CATEGORY"; payload: CategoryType }
  | { type: "UPDATE_BASE_INFO"; payload: Partial<InventoryProduct> }
  | { type: "SET_SPECS"; payload: SpecEntry[] }
  | { type: "ADD_VARIANT" }
  | { type: "REMOVE_VARIANT"; index: number }
  | { type: "UPDATE_VARIANT"; index: number; data: Partial<Variant> }
  | { type: "SET_TAX"; payload: { salesGst: number; hsn: string } };

const initialState: InventoryProduct = {
  brandId: "",
  name: "",
  modelNumber: "",
  categoryId: "electronics", // Primary Department
  category: "smartphone", // Sub-category
  fashionType: "apparel",
  gender: "women",
  warranty: 12,
  hsn: "",
  purchaseGst: 18,
  salesGst: 18,
  features: [],
  // 👗 New Fashion Fields
  selectedSizes: [],
  sizeGuideData: {},
  occasion: "",
  season: "",
  fabric: "",
  // Default Specs for Electronics
  specs: [
    { key: "Display", value: "" },
    { key: "Processor", value: "" },
    { key: "Battery", value: "" },
  ],
  variants: [
    {
      sku: "", // Will be auto-generated by our effect
      color: "#000000",
      colorName: "Black",
      attributes: [
        { key: "RAM", value: "" },
        { key: "Storage", value: "" },
      ],
      baseCost: 0,
      sellingPrice: 0,
      stock: 0,
      reorderLevel: 5,
      images: [],
    },
  ],
  stockUnits: [],
};

export function useProductForm() {
  const [state, dispatch] = useReducer(
    (state: InventoryProduct, action: Action): InventoryProduct => {
      switch (action.type) {
        case "SET_CATEGORY": {
          const newCategory = action.payload;

          // 🎯 Determine the correct config for the new category.
          // Uses getVariantConfig so fashion sub-categories correctly
          // fall back to apparel/footwear/accessories defaults instead of smartphone.
          const config = getVariantConfig(newCategory, state.fashionType);

          // 🔄 MIGRATION LOGIC:
          // Dynamically map existing variant attributes to the new category's keys.
          // This prevents the UI from looking for "RAM" when the category is now "Jeans".
          const morphedVariants = state.variants.map((v) => {
            const newAttributes = config.attributes.map((attr, idx) => ({
              key: attr.key,
              value: v.attributes[idx]?.value || "",
            }));

            return {
              ...v,
              attributes: newAttributes,
            };
          });

          return {
            ...state,
            category: newCategory,
            variants: morphedVariants,
          };
        }

        case "UPDATE_BASE_INFO":
          return { ...state, ...action.payload };

        case "SET_SPECS":
          return { ...state, specs: action.payload };

        case "UPDATE_VARIANT": {
          const newVariants = [...state.variants];
          newVariants[action.index] = {
            ...newVariants[action.index],
            ...action.data,
          };
          return { ...state, variants: newVariants };
        }

        case "ADD_VARIANT": {
          // Uses getVariantConfig so new variants for fashion categories
          // get the correct Size/Fit attributes instead of RAM/Storage.
          const config = getVariantConfig(state.category, state.fashionType);

          // Create new attributes based on current category config
          const newAttributes = config.attributes.map((attr) => ({
            key: attr.key,
            value: "",
          }));

          const newVariant: Variant = {
            ...initialState.variants[0],
            sku: "", // Empty so VariantCard effect triggers generation
            attributes: newAttributes,
          };

          return {
            ...state,
            variants: [...state.variants, newVariant],
          };
        }

        case "REMOVE_VARIANT": {
          if (state.variants.length <= 1) return state;
          const removedSku = state.variants[action.index].sku;
          return {
            ...state,
            variants: state.variants.filter((_, i) => i !== action.index),
            stockUnits: state.stockUnits.filter(
              (u) => u.variantId !== removedSku,
            ),
          };
        }

        case "SET_TAX":
          return {
            ...state,
            salesGst: action.payload.salesGst,
            hsn: action.payload.hsn || state.hsn,
          };

        default:
          return state;
      }
    },
    initialState,
  );

  // 🛡️ DYNAMIC TAXATION EFFECT
  // Automatically updates SalesGST and HSN when hierarchy or price changes.
  useEffect(() => {
    const fetchTax = async () => {
      try {
        const res = await taxApi.calculate({
          department: state.categoryId,
          type: state.fashionType,
          category: state.category,
          sub_category: state.gender,
          selling_price: state.variants[0]?.sellingPrice || 0,
        });

        if (res.success && res.data) {
          dispatch({
            type: "SET_TAX",
            payload: {
              salesGst: res.data.sales_gst,
              hsn: res.data.hsn,
            },
          });
        }
      } catch (error) {
        console.error("Tax calculation failed", error);
      }
    };

    fetchTax();
  }, [
    state.categoryId,
    state.fashionType,
    state.category,
    state.gender,
    state.variants[0]?.sellingPrice,
  ]);

  return { state, dispatch };
}
